// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG6jxKPWuJC1IsGyLpXV86rdyzvi9mhw8',
    appId: '1:443342432609:web:fc924bbda601f8153b7d20',
    messagingSenderId: '443342432609',
    projectId: 'shopping-app-e0bc9',
    authDomain: 'shopping-app-e0bc9.firebaseapp.com',
    storageBucket: 'shopping-app-e0bc9.firebasestorage.app',
    measurementId: 'G-78SJSF5LD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALDeX7hR1M4wNqjbIusGS9zbgqUltYem8',
    appId: '1:443342432609:android:d92301b5e13592293b7d20',
    messagingSenderId: '443342432609',
    projectId: 'shopping-app-e0bc9',
    storageBucket: 'shopping-app-e0bc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz1W9_-SCJBS4ULV_YBto9r7eleCld0K4',
    appId: '1:443342432609:ios:c5a7281fea050a213b7d20',
    messagingSenderId: '443342432609',
    projectId: 'shopping-app-e0bc9',
    storageBucket: 'shopping-app-e0bc9.firebasestorage.app',
    iosBundleId: 'com.example.eComm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz1W9_-SCJBS4ULV_YBto9r7eleCld0K4',
    appId: '1:443342432609:ios:c5a7281fea050a213b7d20',
    messagingSenderId: '443342432609',
    projectId: 'shopping-app-e0bc9',
    storageBucket: 'shopping-app-e0bc9.firebasestorage.app',
    iosBundleId: 'com.example.eComm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG6jxKPWuJC1IsGyLpXV86rdyzvi9mhw8',
    appId: '1:443342432609:web:4e8a8598c5af006b3b7d20',
    messagingSenderId: '443342432609',
    projectId: 'shopping-app-e0bc9',
    authDomain: 'shopping-app-e0bc9.firebaseapp.com',
    storageBucket: 'shopping-app-e0bc9.firebasestorage.app',
    measurementId: 'G-1B35V9N8XC',
  );
}
